export const TokenTypes = {
    KEYWORD: "KEYWORD",
    IDENTIFIER: "IDENTIFIER",
    NUMBER: "NUMBER",
    STRING: "STRING",
    OPERATOR: "OPERATOR",
    PAREN_OPEN: "PAREN_OPEN",
    PAREN_CLOSE: "PAREN_CLOSE",
    BLOCK_OPEN: "BLOCK_OPEN",
    BLOCK_CLOSE: "BLOCK_CLOSE",
    WHITESPACE: "WHITESPACE",
};
  